team-winey/Winey-AOS

- app/build.gradle.kts
- app/src/main/AndroidManifest.xml
- app/src/main/java/com/android/go/sopt/winey/Application.kt
- app/src/main/java/com/android/go/sopt/winey/di/RepositoryModule.kt
- app/src/main/java/com/android/go/sopt/winey/di/RetrofitModule.kt
- app/src/main/java/com/android/go/sopt/winey/di/ServiceModule.kt
- app/src/main/java/com/android/go/sopt/winey/domain/AuthRepository.kt
- app/src/main/java/com/android/go/sopt/winey/presentation/main/MainActivity.kt
- app/src/main/java/com/android/go/sopt/winey/presentation/main/feed/FeedFragment.kt
- app/src/main/java/com/android/go/sopt/winey/presentation/main/feed/FeedViewModel.kt
- app/src/main/java/com/android/go/sopt/winey/presentation/main/mypage/MyPageFragment.kt
- app/src/main/java/com/android/go/sopt/winey/presentation/main/mypage/MyPageViewModel.kt
- app/src/main/java/com/android/go/sopt/winey/presentation/main/recommend/RecommendFragment.kt
- app/src/main/java/com/android/go/sopt/winey/presentation/main/recommend/RecommendViewModel.kt
- app/src/main/res/layout/activity_main.xml
- app/src/main/res/layout/fragment_feed.xml
- app/src/main/res/layout/fragment_my_page.xml
- app/src/main/res/layout/fragment_recommend.xml
- #1 
- 프로젝트 기초 패키징
- domain, di, data, presentation 으로 분류해 hilt 적용+mvvm 구조 지향
- 일단 presentation 안에 메인 뷰 세개 네비게이션바 이름 그대로 해뒀는데 네이밍 좋은 의견있으면 변경해도됩니다 !
> [chore] 기초세팅 / 패키징, hilt 적용

- app/build.gradle.kts
- app/src/main/java/com/android/go/sopt/winey/presentation/main/MainActivity.kt
- app/src/main/java/com/android/go/sopt/winey/presentation/main/feed/FeedFragment.kt
- app/src/main/java/com/android/go/sopt/winey/presentation/main/mypage/MyPageFragment.kt
- app/src/main/java/com/android/go/sopt/winey/presentation/main/recommend/RecommendFragment.kt
- app/src/main/res/layout/activity_main.xml
- app/src/main/res/layout/fragment_feed.xml
- app/src/main/res/layout/fragment_my_page.xml
- app/src/main/res/layout/fragment_recommend.xml
- app/src/main/res/values/themes.xml
- closed #4
- 바인딩 액티비티, 프래그먼트 적용
- 상태바 투명하게 
- 액션바 제거 
- 그레들 수정하는 건 develop 브랜치에서 바로 진행했습니다! 
- 코드 수정한 거 확인하고 리뷰 남겨주세요!
> [mod] 기초세팅 / 바인딩 액티비티, 프래그먼트 적용

- app/src/main/AndroidManifest.xml
- closed #8
- 인터넷 권한 
- HTTP 허용
- 세로 모드 고정 
코드 확인하고 리뷰 남겨주세요!
> [chore] 기초 세팅 / 매니페스트 파일 

- app/src/main/AndroidManifest.xml
- app/src/main/res/values/themes.xml
> [fix] 스타일 네이밍 변경, 오탈자 수정

- app/src/main/java/com/android/go/sopt/winey/data/interceptor/AuthInterceptor.kt
- app/src/main/java/com/android/go/sopt/winey/di/RetrofitModule.kt
- app/src/main/java/com/android/go/sopt/winey/di/qualifier/InterceptorQualifier.kt
- closed #31 
- AuthInterceptor 추가
안드 화이팅 !
> [chore] 서버연결 / AuthInterceptor 추가

- app/src/main/java/com/android/go/sopt/winey/presentation/main/mypage/MyPageViewModel.kt
- app/src/main/java/com/android/go/sopt/winey/presentation/main/mypage/TargetAmountBottomSheetFragment.kt
- app/src/main/java/com/android/go/sopt/winey/presentation/main/mypage/TargetAmountViewModel.kt
- app/src/main/res/drawable/sel_target_amount_til_stroke_color.xml
- app/src/main/res/layout/fragment_target_amount_bottom_sheet.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/values/themes.xml
- closed #41 
조건 만족시 에러메시지 출력
금액 입력 최대 10자리
조건 만족시 버튼 활성화
화면 클릭시 키보드 숨기기
안드 짱
> [feat] 목표설정 바텀시트 / 목표설정 바텀시트 뷰 기능 구현 

- app/src/main/java/com/android/go/sopt/winey/data/model/remote/request/RequestCreateGoalDto.kt
- app/src/main/java/com/android/go/sopt/winey/data/model/remote/response/ResponseCreateGoalDto.kt
- app/src/main/java/com/android/go/sopt/winey/data/model/remote/response/ResponseGetUserDto.kt
- app/src/main/java/com/android/go/sopt/winey/data/repository/AuthRepositoryImpl.kt
- app/src/main/java/com/android/go/sopt/winey/data/service/AuthService.kt
- app/src/main/java/com/android/go/sopt/winey/data/source/AuthDataSource.kt
- app/src/main/java/com/android/go/sopt/winey/domain/entity/Goal.kt
- app/src/main/java/com/android/go/sopt/winey/domain/repository/AuthRepository.kt
- app/src/main/java/com/android/go/sopt/winey/presentation/main/MainActivity.kt
- app/src/main/java/com/android/go/sopt/winey/presentation/main/MainViewModel.kt
- app/src/main/java/com/android/go/sopt/winey/presentation/main/mypage/MyPageFragment.kt
- app/src/main/java/com/android/go/sopt/winey/presentation/main/mypage/MyPageViewModel.kt
- app/src/main/java/com/android/go/sopt/winey/presentation/main/mypage/TargetAmountBottomSheetFragment.kt
- app/src/main/java/com/android/go/sopt/winey/presentation/main/mypage/TargetAmountViewModel.kt
- app/src/main/res/layout/fragment_my_page.xml
- closed #44 
Dto 작성
Goal 데이터 클래스 작성
서비스, 데이터소스, 레포지토리
목표설정 서버연결
메인 뷰모델 구현
목표설정시, 마이페이지에 반영
> [feat] 목표설정 바텀시트/ 목표설정하기 서버연결

- app/src/main/java/com/android/go/sopt/winey/data/model/remote/response/ResponseGetRecommendListDto.kt
- app/src/main/java/com/android/go/sopt/winey/data/model/remote/response/ResponseGetUserDto.kt
- app/src/main/java/com/android/go/sopt/winey/data/repository/AuthRepositoryImpl.kt
- app/src/main/java/com/android/go/sopt/winey/data/service/AuthService.kt
- app/src/main/java/com/android/go/sopt/winey/data/source/AuthDataSource.kt
- app/src/main/java/com/android/go/sopt/winey/domain/entity/User.kt
- app/src/main/java/com/android/go/sopt/winey/domain/repository/AuthRepository.kt
- app/src/main/java/com/android/go/sopt/winey/presentation/main/MainViewModel.kt
- app/src/main/java/com/android/go/sopt/winey/presentation/main/mypage/MyPageFragment.kt
- app/src/main/java/com/android/go/sopt/winey/presentation/main/mypage/TargetAmountViewModel.kt
- app/src/main/java/com/android/go/sopt/winey/presentation/main/recommend/RecommendAdapter.kt
- app/src/main/java/com/android/go/sopt/winey/presentation/main/recommend/RecommendFragment.kt
- app/src/main/java/com/android/go/sopt/winey/presentation/main/recommend/RecommendViewModel.kt
- app/src/main/res/layout/item_recommend_post.xml
- app/src/main/res/values/strings.xml
- closed #58
Dto 작성, 매핑함수 작성
서비스, 데이터소스, 레포지토리 작성
서버통신 구현
아이템 버튼 이벤트 구현
안드 진짜 최고
> [feat] 추천 위니 / 추천 피드 받아오기 서버연결

- app/build.gradle.kts
- app/src/main/java/com/android/go/sopt/winey/data/model/remote/response/ResponseGetUserDto.kt
- app/src/main/java/com/android/go/sopt/winey/data/repository/AuthRepositoryImpl.kt
- leakCanary 디펜던시 삭제 
- 알 수 없는 오류들이 생겨서 leakCanary 디펜던시 삭제했습니다..!
- 자잘한 머지 충돌 해결했습니다.
> [del] 기초 세팅 / leakCanary 디펜던시 삭제

- app/src/main/java/com/android/go/sopt/winey/presentation/main/mypage/MyPageFragment.kt
- app/src/main/java/com/android/go/sopt/winey/presentation/main/mypage/MyPageViewModel.kt
- app/src/main/java/com/android/go/sopt/winey/presentation/main/mypage/MypageHelpActivity.kt
- app/src/main/java/com/android/go/sopt/winey/presentation/main/mypage/TargetAmountBottomSheetFragment.kt
- app/src/main/java/com/android/go/sopt/winey/presentation/main/mypage/TargetAmountViewModel.kt
- app/src/main/java/com/android/go/sopt/winey/presentation/main/recommend/RecommendFragment.kt
- app/src/main/res/layout/fragment_target_amount_bottom_sheet.xml
- app/src/main/res/values/strings.xml
- closed #69 
금액 입력 범위 변경
목표설정 바텀시트 에러 분기 오류 수정
추천위니 어댑터 초기화 방법 변경
안드 짱
> [fix] 마이페이지뷰, 목표설정 바텀시트 / 자잘한 오류 해결, 코드 리팩토링

- app/src/main/java/com/android/go/sopt/winey/util/binding/BindingAdapter.kt
- #68 
이미지 자동 확대 되면서 화질이 깨지는 문제가 있어서 centerCrop으로 스케일 타입 변경했습니다. 
실행 결과 확인 부탁!
> [fix] 위니 업로드 / 이미지뷰 scaleType 조정 

- app/src/main/java/com/android/go/sopt/winey/presentation/main/MainViewModel.kt
- app/src/main/java/com/android/go/sopt/winey/presentation/main/mypage/MyPageFragment.kt
- app/src/main/java/com/android/go/sopt/winey/presentation/main/mypage/MypageFragmentCallback.kt
- app/src/main/java/com/android/go/sopt/winey/presentation/main/mypage/MypageHelpActivity.kt
- app/src/main/java/com/android/go/sopt/winey/presentation/main/mypage/TargetAmountBottomSheetFragment.kt
- app/src/main/java/com/android/go/sopt/winey/presentation/main/mypage/TargetAmountViewModel.kt
> [chore] 사소해 사소해

- app/src/main/java/com/android/go/sopt/winey/presentation/main/feed/upload/amount/AmountViewModel.kt
- app/src/main/res/layout/fragment_amount.xml
- closed #68
- 최대 10글자까지만 입력 허용
> [fix] 위니 업로드 / 금액 최대 길이 설정

- app/src/main/java/com/android/go/sopt/winey/data/interceptor/AuthInterceptor.kt
- app/src/main/java/com/android/go/sopt/winey/presentation/main/mypage/myfeed/MyFeedFragment.kt
> [fix] 프래그먼트 백스택 이슈 해결

- app/src/main/res/layout/item_recommend_header.xml
- app/src/main/res/values/strings.xml
> [ui] #88 디자인 QA 반영

- app/src/main/java/com/android/go/sopt/winey/data/interceptor/AuthInterceptor.kt
- app/src/main/java/com/android/go/sopt/winey/data/model/remote/request/RequestCreateGoalDto.kt
- app/src/main/java/com/android/go/sopt/winey/presentation/main/MainActivity.kt
- app/src/main/java/com/android/go/sopt/winey/presentation/main/MainViewModel.kt
- app/src/main/java/com/android/go/sopt/winey/presentation/main/feed/WineyFeedDialogFragment.kt
- app/src/main/java/com/android/go/sopt/winey/presentation/main/feed/WineyFeedFragment.kt
- app/src/main/java/com/android/go/sopt/winey/presentation/main/mypage/MyPageFragment.kt
- app/src/main/java/com/android/go/sopt/winey/presentation/main/mypage/TargetAmountBottomSheetFragment.kt
- app/src/main/java/com/android/go/sopt/winey/presentation/main/mypage/TargetAmountViewModel.kt
- app/src/main/java/com/android/go/sopt/winey/presentation/main/recommend/RecommendFragment.kt
- app/src/main/java/com/android/go/sopt/winey/presentation/main/recommend/RecommendViewModel.kt
- app/src/main/res/layout/fragment_target_amount_bottom_sheet.xml
- closed #93
- 마이페이지, 추천위니 StateFlow 사용
- 프래그먼트 이동시, 바텀네비게이션 아이콘 동기화
뒤로가기 버튼을 눌렀을때나, 목표설정 다이얼로그에서 마이페이지로 이동하였을때 바텀네비게이션 아이콘도 따라서 변경되도록 하였습니다.
> [refactor] 마이페이지, 추천위니 / 리팩토링

- app/src/main/res/drawable/ic_recommend_item_saver.xml
- app/src/main/res/layout/fragment_my_page.xml
- app/src/main/res/layout/fragment_target_amount_bottom_sheet.xml
- app/src/main/res/layout/item_recommend_header.xml
- app/src/main/res/values/strings.xml
- closed #104
변경된 디자인에 맞게 리디자인
마이페이지 뷰 리디자인
추천 뷰 리디자인
확인해주시면 바로 머지하겠습니다 !
> [ui] 마이페이지 뷰, 추천 뷰 / 변경된 디자인에 맞게 리디자인

- app/src/main/java/com/android/go/sopt/winey/data/model/remote/response/ResponseDeleteCommentDto.kt
- app/src/main/java/com/android/go/sopt/winey/data/model/remote/response/ResponseDeleteWineyFeedDto.kt
- app/src/main/java/com/android/go/sopt/winey/data/repository/FeedRepositoryImpl.kt
- app/src/main/java/com/android/go/sopt/winey/data/service/FeedService.kt
- app/src/main/java/com/android/go/sopt/winey/data/source/FeedDataSource.kt
- app/src/main/java/com/android/go/sopt/winey/domain/repository/FeedRepository.kt
- app/src/main/java/com/android/go/sopt/winey/presentation/main/MainActivity.kt
- app/src/main/java/com/android/go/sopt/winey/presentation/main/feed/WineyFeedFragment.kt
- app/src/main/java/com/android/go/sopt/winey/presentation/main/feed/detail/CommentAdapter.kt
- app/src/main/java/com/android/go/sopt/winey/presentation/main/feed/detail/DetailActivity.kt
- app/src/main/java/com/android/go/sopt/winey/presentation/main/feed/detail/DetailFeedAdapter.kt
- app/src/main/java/com/android/go/sopt/winey/presentation/main/feed/detail/DetailViewModel.kt
- app/src/main/res/layout/item_detail_feed.xml
- app/src/main/res/layout/item_myfeed_post.xml
- app/src/main/res/layout/item_wineyfeed_post.xml
- closed #133 
- 댓글 삭제 
- 댓글 신고 
- 자세한 작업 내용은 이슈에 적어둔 내용 참고해주세요! 
- 댓글이 있다가 삭제되었을 때, "댓글이 아직 없어요" 뷰가 뜨게 만드는 건 곧 반영하겠습니다!! 
- 피드 좋아요/취소, 댓글 개수 등 리사이클러뷰 아이템 갱신할 때, 이미지가 깜박거리는 현상 해결했습니다! 코드 참고해주세요!
> [feat] 상세 피드 / 댓글 삭제 및 신고 기능 구현 

- app/src/main/java/com/android/go/sopt/winey/presentation/main/MainActivity.kt
- app/src/main/java/com/android/go/sopt/winey/presentation/main/feed/detail/DetailActivity.kt
- app/src/main/java/com/android/go/sopt/winey/presentation/main/mypage/MyPageFragment.kt
- app/src/main/java/com/android/go/sopt/winey/presentation/main/notification/NotificationActivity.kt
- app/src/main/java/com/android/go/sopt/winey/presentation/main/notification/NotificationAdapter.kt
- closed #141
자기 자신이 좋아요 누른 경우에도 알림이 보이는것 변경
알림 누르고 들어간 게시물이 삭제됐을 시 처리
알림 -> 마이페이지에서 뒤로가기 눌렀을 시 다시 알림페이지로 돌아가기
목표 설정 불가 다이얼로그 띄우기
> [fix] 알림 / 알림 기능 오류 수정

- app/src/main/java/com/android/go/sopt/winey/presentation/main/feed/upload/PhotoFragment.kt
- app/src/main/java/com/android/go/sopt/winey/presentation/main/feed/upload/UploadActivity.kt
- closed #156 
- 커밋 하나밖에 안 했어요! 
- 기획 파트 큐에이 반영했습니다! 
- 변경 사항 확인 부탁드려요 :)
> [mod] 위니 업로드 / 사진 업로드 프래그먼트에서만 경고 다이얼로그가 뜨도록 변경

- app/src/main/java/com/android/go/sopt/winey/presentation/main/notification/NotificationActivity.kt
- app/src/main/res/layout/activity_notification.xml
- closed #164
- 알림 뷰 스와이프 새로고침 기능추가(ios와 통일)
> [feat] 알림 / 스와이프 새로고침 기능추가

- app/src/main/java/org/go/sopt/winey/presentation/main/feed/WineyFeedFragment.kt
- app/src/main/java/org/go/sopt/winey/presentation/nickname/NicknameActivity.kt
- app/src/main/java/org/go/sopt/winey/util/binding/BindingAdapter.kt
- app/src/main/res/layout/activity_nickname.xml
- closed #186 
- 아요, 기획 파트 의견에 따라 힌트 텍스트도 글자수 카운팅 해서 우측에 표시하기로 했습니다! 
- 오늘 자정까지 확인 부탁해요~~!!
> [mod] 마이페이지 / 닉네임 수정 뷰에서 원래 닉네임의 글자수 표시

- app/src/main/java/org/go/sopt/winey/presentation/main/feed/upload/AmountFragment.kt
- app/src/main/java/org/go/sopt/winey/presentation/main/feed/upload/UploadViewModel.kt
- app/src/main/java/org/go/sopt/winey/presentation/onboarding/story/StoryActivity.kt
- app/src/main/java/org/go/sopt/winey/util/binding/BindingAdapter.kt
- app/src/main/java/org/go/sopt/winey/util/multipart/UriToRequestBody.kt
- app/src/main/res/layout/activity_nickname.xml
- closed #188 
- 이슈 내용 확인 해주세요!
- 현재 코드에 혜선이 PR이 머지되어 있기 때문에, 혜선이가 코드 수정해서 먼저 디벨롭에 머지하고, 
- 제가 그걸 다시 풀 받은 다음에 푸시하고 머지해야 할 거 같습니다!
> [fix] 위니 업로드 / 이미지 크기가 5MB 보다 작은 경우 

- app/build.gradle.kts
- closed #208 
- 앱 경량화, 난독화 코드 추가
디버그 빌드에도 적용하는 경우도 있다고 하는데
일단 릴리즈 빌드에만 적용했습니다 ~!
> [add] 기초 세팅 / R8컴파일러로 앱 경량화, 난독화

- app/src/main/java/org/go/sopt/winey/presentation/main/mypage/MyPageFragment.kt
- 마이페이지 목표 설정 관련해서 주석에 설명을 조금 덧붙였습니다! 
- 혹시나 제가 잘못 이해하고 작성한 부분이 있다면 알려주세요!
> [comment] 마이페이지 / 목표설정 관련 주석 수정

- app/build.gradle.kts
- app/release/output-metadata.json
- app/src/main/java/org/go/sopt/winey/presentation/main/feed/WineyFeedFragment.kt
- app/src/main/java/org/go/sopt/winey/presentation/main/feed/detail/DetailActivity.kt
- app/src/main/java/org/go/sopt/winey/presentation/main/mypage/MyPageFragment.kt
- app/src/main/java/org/go/sopt/winey/util/binding/BindingDialogFragment.kt
- app/src/main/res/values/strings.xml
- buildSrc/src/main/java/DefaultConfig.kt
- closed #207 
- closed #212 
- 이슈 내용 확인 부탁드립니다!! :)
- 버전 코드와 버전 이름 수정했고, 1.0.1 버전으로 게시할 예정입니다!
> [feat] 위니 피드 / 기간 내 목표 달성 시 축하 다이얼로그 띄우기 

- app/proguard-rules.pro
- app/release/output-metadata.json
- buildSrc/src/main/java/DefaultConfig.kt
- closed #214 
크래시 방지를 위해 proguar-rules를 추가합니다
- kakao SDK proguard rule 
- retrofit proguard rule 
- okhttp proguard rule
내부테스트앱 만들고 정상적으로 실행되면 머지할게요 ~!
> [fix] 기초 세팅 / 난독화 후 앱 크래시 현상 해결

- app/proguard-rules.pro
- app/src/main/java/org/go/sopt/winey/data/source/KakaoLoginDataSource.kt
- app/src/main/java/org/go/sopt/winey/di/ServiceModule.kt
- closed #218 
- 의존성 주입 관련 오류 수정
- 프로가드 룰 추가
해결 됐으면 좋겠다 . . .
> [fix] 카카오 로그인 오류 수정

- app/src/main/java/org/go/sopt/winey/presentation/main/feed/WineyFeedFragment.kt
- app/src/main/java/org/go/sopt/winey/presentation/main/feed/detail/DetailActivity.kt
- app/src/main/java/org/go/sopt/winey/presentation/main/feed/upload/PhotoFragment.kt
- app/src/main/java/org/go/sopt/winey/presentation/main/mypage/MyPageFragment.kt
- app/src/main/java/org/go/sopt/winey/presentation/main/mypage/myfeed/MyFeedFragment.kt
- app/src/main/java/org/go/sopt/winey/presentation/model/WineyDialogLabel.kt
- app/src/main/java/org/go/sopt/winey/util/fragment/WineyDialogFragment.kt
- app/src/main/java/org/go/sopt/winey/util/intent/ArgsExt.kt
- app/src/main/java/org/go/sopt/winey/util/intent/IntentExt.kt
- app/src/main/res/layout/fragment_alert_dialog.xml
- closed #224
- 프래그먼트 생성자 사용하지 않고 newInstance의 번들로 넘겨주기
프래그먼트는 생성자를 이용할경우 상태변화등에 크래시 가능성이 있어서 번들로 전달해주는 방식으로 리팩토링 해주었습니다.
> [refactor] 위니 다이얼로그 프래그먼트 / 생성자 사용하지 않고 번들 사용하기

- app/src/main/res/drawable/ic_wineyfeed_notification_new.xml
- closed #250 
- 아이콘 드로어블 파일 변경
- 간단히 확인 부탁드려요 :)
> [ui] 알림 뱃지 아이콘 색상 변경

- app/src/main/java/org/go/sopt/winey/presentation/main/mypage/MyPageFragment.kt
- closed #275 
- is2weekGraphAnimating이라는 플래그로 애니메이션 실행 여부 관리
- 자세한 사항은 이슈 확인해주세요 ~ 😽
> [fix] 마이페이지 / 2주 절약, 소비 애니메이션 깜빡임 현상 해결

- app/src/main/java/org/go/sopt/winey/presentation/main/mypage/goal/GoalPathActivity.kt
- app/src/main/res/layout/activity_goal_path.xml
- app/src/main/res/values/strings.xml
- closed #281
- 빠르게 QA 사항 반영 완료했습니다! 
- 내일까지 확인 부탁해요!!
> [mod] 목표 여정 / 황제 레벨 가이드 박스 변경

- buildSrc/src/main/java/Testing.kt
- closed #291
- 이슈 확인 부탁해요! 
- 이 부분까지 반영해서 aab 파일 추출했고, 스토어에 심사 요청 보낸 상태입니다! 그래서 메인 브랜치 방향으로 pr 올렸습니다! 
- 디펜던시 버전 업그레이드 했을 때 혹시 다른 문제가 생기지는 않는지 확인 부탁드려요! (저는 현재 젤리피쉬 버전의 안스 사용하고 있어요)
> [hotfix] junit test 디펜던시 버전 업그레이드

- app/src/main/res/layout/activity_setting.xml
- 깃허브에 v1.1.0 릴리즈 노트 작성하려고 apk 파일 추출하던 중에 뒤늦게 xml 오류가 발견되었어요..!! 
- 설명 화면 xml에서 ConstraintLayout 제약 조건이 잘못 걸려있는 게 한 줄 있더라구요 🧐
- 다소 번거롭지만,, develop, main 브랜치 방향으로 모두 머지하겠습니다!!
> [fix] 설정 화면 / ConstraintLayout 제약 조건 오류 수정

- app/release/output-metadata.json
- buildSrc/src/main/java/DefaultConfig.kt
- closed #314
콘솔 내부 테스트까지 완료되어 프로덕션 버전으로 출시하겠습니다.
> [mod] 서버 주소 변경 
